CREATE TABLE IF NOT EXISTS public.caliaire_registros (
    id integer GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    idb integer NOT NULL,
    humedad numeric(10,4) NOT NULL,
    temperatura_c numeric(10,4) NOT NULL,
    dioxido_carbono_ppm numeric(10,4) NOT NULL,
    fecha_registro timestamp with time zone NOT NULL
);

CREATE TABLE IF NOT EXISTS public.cupe_registros (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cam_id text NOT NULL,
    ts timestamp with time zone NOT NULL,
    aforo smallint
);

CREATE TABLE IF NOT EXISTS public.sp_registros (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cam_id text NOT NULL,
    ts timestamp with time zone NOT NULL,
    spots_state text NOT NULL,
    spot_ids text[] NOT NULL,
    layout integer[] NOT NULL
);

CREATE TABLE IF NOT EXISTS public.test (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name text
);

CREATE INDEX IF NOT EXISTS idx_caliaire_idb_ts_desc
    ON public.caliaire_registros (idb, fecha_registro DESC);

CREATE INDEX IF NOT EXISTS idx_cupe_cam_ts_desc
    ON public.cupe_registros (cam_id, ts DESC);

CREATE INDEX IF NOT EXISTS idx_sp_cam_ts_desc
    ON public.sp_registros (cam_id, ts DESC);