#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_ADMIN_USER" --dbname "$POSTGRES_DB" <<EOSQL
DO \$\$
BEGIN
    IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname = '${POSTGRES_READ_USER}') THEN
        CREATE ROLE ${POSTGRES_READ_USER} LOGIN PASSWORD '${POSTGRES_READ_PASSWORD}';
    END IF;
END
\$\$;

DO \$\$
BEGIN
    IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname = '${POSTGRES_WRITE_USER}') THEN
        CREATE ROLE ${POSTGRES_WRITE_USER} LOGIN PASSWORD '${POSTGRES_WRITE_PASSWORD}';
    END IF;
END
\$\$;

GRANT CONNECT ON DATABASE ${POSTGRES_DB} TO ${POSTGRES_READ_USER};
GRANT CONNECT ON DATABASE ${POSTGRES_DB} TO ${POSTGRES_WRITE_USER};

GRANT USAGE ON SCHEMA public TO ${POSTGRES_READ_USER};
GRANT USAGE ON SCHEMA public TO ${POSTGRES_WRITE_USER};

GRANT SELECT ON ALL TABLES IN SCHEMA public TO ${POSTGRES_READ_USER};
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO ${POSTGRES_WRITE_USER};

GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO ${POSTGRES_READ_USER};
GRANT USAGE, SELECT, UPDATE ON ALL SEQUENCES IN SCHEMA public TO ${POSTGRES_WRITE_USER};

ALTER DEFAULT PRIVILEGES FOR ROLE ${POSTGRES_ADMIN_USER} IN SCHEMA public
GRANT SELECT ON TABLES TO ${POSTGRES_READ_USER};

ALTER DEFAULT PRIVILEGES FOR ROLE ${POSTGRES_ADMIN_USER} IN SCHEMA public
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO ${POSTGRES_WRITE_USER};

ALTER DEFAULT PRIVILEGES FOR ROLE ${POSTGRES_ADMIN_USER} IN SCHEMA public
GRANT USAGE, SELECT ON SEQUENCES TO ${POSTGRES_READ_USER};

ALTER DEFAULT PRIVILEGES FOR ROLE ${POSTGRES_ADMIN_USER} IN SCHEMA public
GRANT USAGE, SELECT, UPDATE ON SEQUENCES TO ${POSTGRES_WRITE_USER};
EOSQL